version: "3"
services:
    app:
        build: .
        image: php-app
        ports:
            - "8000:8000"
        volumes:
            - .:/app

    db:
        image: mariadb
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=blog
            - MYSQL_USER=tai
            - MYSQL_PASSWORD=root
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
